import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Item from '../components/Item';
import { google } from 'googleapis';
import { getAuthToken } from '../googleapi/getAuthToken';

const CONSTANTS_NAMES = [
  { name: "pH", unit: "" },
  { name: "Chlore", unit: "ppm" },
  { name: "Temperature", unit: "°C"},
  { name: "Chaussette", unit: "" },
  { name: "Robot", unit: "" }
];

export async function getServerSideProps() {

  const auth = await getAuthToken();

  const sheets = google.sheets({ version: 'v4', auth });

  const history = CONSTANTS_NAMES.reduce((acc, curr) => (acc[curr.name] = [], acc), {});

  await Promise.all(CONSTANTS_NAMES.map(async (constant) => {
    const response = await sheets.spreadsheets.values.get({
      spreadsheetId: process.env.SHEET_ID,
      range: constant.name + '!A2:B',
    });

    const values = response.data.values;
    history[constant.name] = values;
  }));

  return {
    props: {
      history,
    },
  };
}

function renderItems(history) {
  let items = [];
  for (const [key, value] of Object.entries(CONSTANTS_NAMES)) {
    const values = history[value.name];
    const lastValue = values[values.length - 1];
    items.push(<Item name={value.name} value={lastValue[1]} unit={value.unit} date={lastValue[0]} history={history[value.name]} key={value.name}/>)
  }
  return items;
}

export default function Home({ history }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pool Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className="App-header">
          <h1>Pool Tracker</h1>
        </header>
        <div className="dashboard">
          {renderItems(history)}
        </div>
      </main>

      <footer className={styles.footer}><a href="https://docs.google.com/spreadsheets/d/1rSOukLsKhWbSnEZ2A8HBd-aYVikfa2rVaT5OpCRd7t8/edit?usp=sharing">Données</a></footer>
    </div>
  )
}
